name: musilingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Backend & Services
  supabase_flutter: ^2.9.1

  # State Management & UI
  provider: ^6.1.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  drag_and_drop_lists: ^0.4.2
  collection: ^1.18.0
  image_picker: ^1.1.2
  confetti: ^0.7.0
  just_audio: ^0.10.4
  webview_flutter: ^4.8.0
  flutter_midi_pro: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  supabase: ^2.1.2
  yaml: ^3.1.2
  dotenv: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sf2/GeneralUserGS.sf2
    - assets/web/
    - assets/web/js/