name: musilingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Backend & Services
  supabase_flutter: ^2.9.1

  # UI & UX
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  just_audio: ^0.10.4
  drag_and_drop_lists: ^0.4.2 # <-- DEPENDÊNCIA ATUALIZADA/ADICIONADA
  collection: ^1.18.0         # <-- DEPENDÊNCIA ADICIONADA

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  supabase: ^2.1.2  # Adicione esta linha
  yaml: ^3.1.2      # Adicione esta linha
  dotenv: ^4.2.0    # Adicione esta linha

flutter:
  uses-material-design: true

  assets:
    - assets/images/
