name: musilingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Backend & Services
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.0.2

  # State Management & UI
  provider: ^6.1.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  drag_and_drop_lists: ^0.4.2
  image_picker: ^1.1.2
  confetti: ^0.7.0
  just_audio: ^0.10.4
  flutter_midi_pro: ^3.1.4
  intl: ^0.19.0
  audioplayers: ^6.5.0
  
  # NOVA DEPENDÊNCIA PARA O SOLFEJO
  pitch_detector_dart: ^0.0.7
  record: ^6.1.1

  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  
  # Speech Recognition
  speech_to_text: ^6.3.0
  
  # FFT for pitch detection
  fftea: ^1.5.0+1
  
  # WebView for OSMD
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.9.4
  
  # MIDI playback
  flutter_midi: ^1.1.0
  
  # Utilities
  collection: ^1.17.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  supabase: ^2.1.2
  yaml: ^3.1.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/sf2/GeneralUserGS.sf2
    - assets/audio/
    - assets/osmd_viewer/ # <--- SUBSTITUA a linha do score_renderer por esta
    - assets/osmd_viewer/js/ # <--- E adicione esta
